#!/usr/bin/env bash
# Hosts dosyasının
[ "$EUID" -ne 0 ] && echo "Script root olarak çalıştırılmalı (sudo)." && exit 1

HOSTS_FILE="/etc/hosts"
TMP_FILE="/tmp/hosts.tmp"

# Yedek al
cp "$HOSTS_FILE" "${HOSTS_FILE}.bak"

# Yeni dosya oluştur
grep -v "127.0.0.1\s\+localhost" "$HOSTS_FILE" | grep -v "facebook\.com" > "$TMP_FILE"

# Yeni kayıtları ekle
echo "127.0.0.2   localhost" >> "$TMP_FILE"
echo "8.8.8.8     facebook.com" >> "$TMP_FILE"

# Dosyayı geri yaz
cat "$TMP_FILE" > "$HOSTS_FILE"
rm "$TMP_FILE"

echo "localhost ve facebook.com yönlendirmeleri ayarlandı."
