#!/bin/bash/env bash

# Netcat ile localhost üzerinde 127.0.0.1:98 portunu dinle
# -k : Bağlantı kapansa bile dinlemeye devam et
# -l : Dinleme moduna geç
# -p : Portu belirt
# -s : Sadece belirtilen IP'den gelenleri dinle
nc -l -s 127.0.0.1 -p 98

